DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS lab_result;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE lab_result (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
   INTEGER NOT NULL,
  sample_id TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  thc FLOAT NOT NULL,
  cbd FLOAT NOT NULL,
  cbn FLOAT NOT NULL,
  cbg FLOAT NOT NULL,
  cbc FLOAT NOT NULL,
  thca FLOAT NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
